# Generated by Django 2.1.7 on 2019-03-25 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImsSalesOrderItem',
            fields=[
                ('id_sales_order_item', models.IntegerField(primary_key=True, serialize=False)),
                ('bob_id_sales_order_item', models.IntegerField()),
                ('fk_sales_order', models.IntegerField()),
                ('fk_delivery_type', models.IntegerField()),
                ('unit_price', models.FloatField(max_length=250)),
                ('tax_amount', models.IntegerField()),
                ('paid_price', models.FloatField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('sku', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(max_length=250)),
                ('updated_at', models.DateTimeField(max_length=250)),
                ('last_status_change', models.DateTimeField(max_length=250)),
                ('original_unit_price', models.FloatField(max_length=250)),
                ('shipping_type', models.CharField(max_length=250)),
                ('real_delivery_date', models.DateTimeField(max_length=100, null=True)),
                ('bob_id_supplier', models.IntegerField()),
                ('is_marketplace', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ImsSalesOrderItemStatus',
            fields=[
                ('id_sales_order_item_status', models.IntegerField(primary_key=True, serialize=False)),
                ('fk_oms_function', models.IntegerField()),
                ('status', models.CharField(max_length=250)),
                ('desc', models.CharField(max_length=250)),
                ('deprecated', models.CharField(max_length=250)),
                ('updated_at', models.DateTimeField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ImsSalesOrderItemStatusHistory',
            fields=[
                ('id_sales_order_item_status_history', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(max_length=100, null=True)),
                ('fk_sales_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam_app.ImsSalesOrderItem')),
                ('fk_sales_order_item_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam_app.ImsSalesOrderItemStatus')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=250)),
                ('major_region', models.CharField(max_length=250)),
                ('package_number', models.CharField(max_length=250)),
                ('shipped_at', models.DateTimeField(max_length=250)),
                ('delivered_at', models.DateTimeField(max_length=250)),
                ('leadtime', models.FloatField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=250)),
                ('major_region', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='imssalesorderitem',
            name='fk_sales_order_item_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam_app.ImsSalesOrderItemStatus'),
        ),
    ]
